version: '3.7'

x-common: &common
  env_file: .env.dev.docker
  build:
    context: .
    dockerfile: ./docker/development/Dockerfile

services:
  db:
    image: postgres:13.3
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=portfolio
      - POSTGRES_DB=portfolio_development
      - POSTGRES_PASSWORD=password
    ports:
      - 5431:5432
  web:
    <<: *common
    command: ["bundle exec rails server -b 0.0.0.0"]
    volumes:
      - .:/portfolio:delegated
    ports:
      - "3001:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true